### PR TITLE
Make it work on non-enlgish locales

### PR DESCRIPTION
**Pull request by virus-found**
Script just does nothing on de_DE.UTF-8 and all other ones

### CODE REVIEW

**Review by dr0i — COMMENTED** [review]
Thx for the catch - you are right, it's not working on one of my machines.
I tested your proposal, but also without success. I think the missing "export"ing of the variable is the crucial point.

Pushed the following changes into master:

- exporting the variable ("export LC_ALL=C")
- added a small test in the script

You may want to run that newest version of the script and  give a note of it's outcome.

**Comment by dsptiv** [comment]
Hi, dr0i,
Thanks for this repo!

It's still not working. I'm in Ubuntu 20.04, system in en_US.UTF8 and locale would be pt_BR.UTF8. The LC_ALL=C gives the following output:

##
stat: cannot stat 'README.md': No such file or directory
There are problems with your language settings. The 'stat' command must answer in English,
i.e. 'regular file' but it's answer was ' '.
You may want to open an issue and ask for further assistance. Then, please paste this into the
 issue:
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
##

I've tested all combinations of LC_ALL with en_US and pt_BR, as well as export LANG and LANGUAGE to C together with and without LC_ALL=C, but none have worked.

**Comment by dr0i** [comment]
> stat: cannot stat 'README.md': No such file or directory

means what it says: it cannot access the file `README.md`.
The script is supposed to be started from the directory where it resides.
Don't do something like: `bash $myDir/copy-from-time-machine.sh`.

Can you try it again?

**Comment by dsptiv** [comment]
sorry,

here are command and result, with the script in my user home folder.

`daniel@macmini:~$ sudo ./copy-from-time-machine.sh '/media/daniel/Nàrback2/Backups.backupdb/iMac de Daniel/Latest' /media/daniel/untitled/rescue
`
`HFS Private Directory Data found in '/media/daniel/Nàrback2'
`

It stops at this info and runs no further.

If pointed to

`'/media/daniel/Nàrback2/.HFS+ Private Directory Data\r/'
`

it does nothing.

**Comment by dsptiv** [comment]
Hi, dr0i,

It works, with these options in the corresponding session of the script (my local for the Time Machine backup being Brazil):

`LC_ALL=C`
`LANG=pt_BR.UTF8`

All the best!

**Comment by dr0i** [comment]
@dsptiv

**Comment by dr0i** [comment]
I declined the PR because it would only work on English systems.
Opened a new issue: https://github.com/dr0i/copy-from-mac-time-machine/issues/3.

**Comment by thatoo-apple** [comment]
> Hi, dr0i,
> 
> It works, with these options in the corresponding session of the script (my local for the Time Machine backup being Brazil):
> 
> `LC_ALL=C`
> `LANG=pt_BR.UTF8`
> 
> All the best!

Hey, I have tried that you said, but I'm still getting the same issue. Can you give me a little help?  Is it "Lang" variable from the Mac or the ubuntu?

my output for "locale":`LANG=C.UTF-8
LANGUAGE=pt_BR:pt:en
LC_CTYPE=C.UTF-8
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=`

**Comment by dr0i** [comment]
I assume you execute the script on the Ubuntu/Linux machine.
Your output of `LC_ALL=` indicates that you haven't set this like `LC_ALL=C`. Try this first.

**Pull request closed without merging**
